ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS delivery_type VARCHAR DEFAULT 'line';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS email_subject VARCHAR DEFAULT '';
ALTER TABLE message_logs ADD COLUMN IF NOT EXISTS delivery_type VARCHAR DEFAULT 'line';
ALTER TABLE message_logs ADD COLUMN IF NOT EXISTS email VARCHAR DEFAULT '';
